// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsdvZsNMiD0skNpVKbNJlGGBmQ6kbqfBg',
    appId: '1:962981084599:web:169a99a0b2c182ac973c32',
    messagingSenderId: '962981084599',
    projectId: 'mana-lanches-6455e',
    authDomain: 'mana-lanches-6455e.firebaseapp.com',
    storageBucket: 'mana-lanches-6455e.firebasestorage.app',
    measurementId: 'G-FZMLKRXVCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEqRB6_7z4vxiC8bxAjSSZcQ9Q3p81rZs',
    appId: '1:962981084599:android:130e9621117ace9a973c32',
    messagingSenderId: '962981084599',
    projectId: 'mana-lanches-6455e',
    storageBucket: 'mana-lanches-6455e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMuoFVWjBvHYrznwvStMTZ1GVf05mQAU',
    appId: '1:962981084599:ios:a194531a0ae0eae9973c32',
    messagingSenderId: '962981084599',
    projectId: 'mana-lanches-6455e',
    storageBucket: 'mana-lanches-6455e.firebasestorage.app',
    iosBundleId: 'com.example.manaLanche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMuoFVWjBvHYrznwvStMTZ1GVf05mQAU',
    appId: '1:962981084599:ios:a194531a0ae0eae9973c32',
    messagingSenderId: '962981084599',
    projectId: 'mana-lanches-6455e',
    storageBucket: 'mana-lanches-6455e.firebasestorage.app',
    iosBundleId: 'com.example.manaLanche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsdvZsNMiD0skNpVKbNJlGGBmQ6kbqfBg',
    appId: '1:962981084599:web:e80804a072e385c4973c32',
    messagingSenderId: '962981084599',
    projectId: 'mana-lanches-6455e',
    authDomain: 'mana-lanches-6455e.firebaseapp.com',
    storageBucket: 'mana-lanches-6455e.firebasestorage.app',
    measurementId: 'G-GMREZ41MDQ',
  );
}
